# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'BecaWeekMovies' do
  use_frameworks!


  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'
  
end
